<script type="text/javascript"
	src="resources/js/data_table/jquery.dataTables.min.js"></script>
<script type="text/javascript"
	src="resources/js/data_table/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript"
	src="resources/js/data_table/dataTables.responsive.min.js"></script>
<script type="text/javascript"
	src="resources/js/data_table/responsive.bootstrap4.min.js"></script>
<script type="text/javascript"
	src="resources/js/data_table/data_table.js"></script>